using Play.Catalog.Service.Entities;
using Play.Common.MassTransit;
using Play.Common.MongoDB;

var builder = WebApplication.CreateBuilder(args);

// Add Mongo and MassTransit in services
builder.Services.AddMongo(builder.Configuration)
    .AddMongoRepository<Item>("items")
    .AddMassTransitWithRabbitMq(builder.Configuration);

// Configure Suppress Async Suffix in services
builder.Services.AddControllers(options =>
{
    options.SuppressAsyncSuffixInActionNames = false;
});

// Add services to the container.
builder.Services.AddControllers();

// Learn more about configuring OpenAPI at https://aka.ms/aspnet/openapi
builder.Services.AddOpenApi();

// Optional but recommended: enables better Swagger integration & customization
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    // Exposes the native OpenAPI document (e.g. /openapi/v1.json)
    app.MapOpenApi();

    // Enables Swagger UI – points to the native OpenAPI endpoint
    app.UseSwagger();
    app.UseSwaggerUI(options =>
    {
        // Use the document generated by Microsoft.AspNetCore.OpenApi
        options.SwaggerEndpoint("/openapi/v1.json", "My API v1");

        // Optional: make Swagger UI appear at the root URL[](http://localhost:<port>/)
        options.RoutePrefix = string.Empty;

        // Optional extras (uncomment if needed)
        // options.DisplayRequestDuration();           // shows timing
        // options.EnableTryItOutByDefault();          // auto-expands Try it out
        // options.EnableDeepLinking();                // better navigation
    });
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();