using MongoDB.Bson;
using MongoDB.Bson.Serialization;
using MongoDB.Bson.Serialization.Serializers;
using MongoDB.Driver;
using Play.Catalog.Service.Repositories;
using Play.Catalog.Service.Settings;

// ────────────────────────────────────────────────
// Register a default Guid serializer (helps in some edge cases like ObjectSerializer internals)
BsonSerializer.RegisterSerializer(new GuidSerializer(GuidRepresentation.Standard));
// ────────────────────────────────────────────────

var builder = WebApplication.CreateBuilder(args);

// ────────────────────────────────────────────────
// Bind the "ServiceSettings" section → strongly-typed options
builder.Services.Configure<ServiceSettings>(
    builder.Configuration.GetSection(nameof(ServiceSettings))
);
// ────────────────────────────────────────────────

builder.Services.AddSingleton(serviceProvider =>
{
    var mongoDbSettings = builder.Configuration.GetSection(nameof(MongoDbSettings)).Get<MongoDbSettings>();
    var mongoClient = new MongoClient(mongoDbSettings.ConnectionString);
    var serviceSettings = builder.Configuration
        .GetSection(nameof(ServiceSettings))
        .Get<ServiceSettings>();
    return mongoClient.GetDatabase(serviceSettings.ServiceName);
});

builder.Services.AddSingleton<IItemsRepository, ItemsRepository>();

// Add services (what was in ConfigureServices)
builder.Services.AddControllers(options =>
{
    options.SuppressAsyncSuffixInActionNames = false;
});

// Add services to the container.
builder.Services.AddControllers();

// Learn more about configuring OpenAPI at https://aka.ms/aspnet/openapi
builder.Services.AddOpenApi();

// Optional but recommended: enables better Swagger integration & customization
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    // Exposes the native OpenAPI document (e.g. /openapi/v1.json)
    app.MapOpenApi();

    // Enables Swagger UI – points to the native OpenAPI endpoint
    app.UseSwagger();
    app.UseSwaggerUI(options =>
    {
        // Use the document generated by Microsoft.AspNetCore.OpenApi
        options.SwaggerEndpoint("/openapi/v1.json", "My API v1");

        // Optional: make Swagger UI appear at the root URL[](http://localhost:<port>/)
        options.RoutePrefix = string.Empty;

        // Optional extras (uncomment if needed)
        // options.DisplayRequestDuration();           // shows timing
        // options.EnableTryItOutByDefault();          // auto-expands Try it out
        // options.EnableDeepLinking();                // better navigation
    });
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();