using Play.Common.MongoDB;
using Play.Inventory.Service.Clients;
using Play.Inventory.Service.Entities;
using Polly;
using Polly.Extensions.Http;
using Polly.Timeout;

var builder = WebApplication.CreateBuilder(args);

// Add Mongo in services
builder.Services.AddMongo(builder.Configuration)
    .AddMongoRepository<InventoryItem>("inventoryitems");

// Configure Suppress Async Suffix in services
builder.Services.AddControllers(options =>
{
    options.SuppressAsyncSuffixInActionNames = false;
});

// Catalog microservice client url
builder.Services.AddHttpClient<CatalogClient>(client =>
{
    client.BaseAddress = new Uri("http://localhost:5160");
})
.AddPolicyHandler((services, request) =>
{
    var logger = services.GetRequiredService<ILogger<CatalogClient>>();

    var timeoutPolicy = Policy.TimeoutAsync<HttpResponseMessage>(TimeSpan.FromSeconds(1));

    Random jitterer = new Random();
    
    var retryPolicy = HttpPolicyExtensions
        .HandleTransientHttpError()
        .Or<TimeoutRejectedException>()
        .WaitAndRetryAsync(
            retryCount: 5,
            sleepDurationProvider: retryAttempt => TimeSpan.FromSeconds(Math.Pow(2, retryAttempt))
                                                   + TimeSpan.FromMilliseconds(jitterer.Next(0, 1000)),
            onRetry: (outcome, timeSpan, retryAttempt, context) =>
            {
                logger.LogWarning(
                    $"Delaying for {timeSpan.TotalSeconds} seconds, then making retry {retryAttempt}."
                );
            }
        );

    var circuitBreakerPolicy = HttpPolicyExtensions
        .HandleTransientHttpError()
        .Or<TimeoutRejectedException>()
        .CircuitBreakerAsync(
            handledEventsAllowedBeforeBreaking: 3,
            durationOfBreak: TimeSpan.FromSeconds(15),
            onBreak: (outcome, timeSpan) =>
            {
                logger.LogWarning(
                    $"Opening the circuit for {timeSpan.TotalSeconds} seconds."
                );
            },
            onReset: () =>
            {
                logger.LogWarning(
                    "Closing the circuit."
                );
            }
        );

    return Policy.WrapAsync(retryPolicy, circuitBreakerPolicy, timeoutPolicy);
});

// Add services to the container.
builder.Services.AddControllers();

// Learn more about configuring OpenAPI at https://aka.ms/aspnet/openapi
builder.Services.AddOpenApi();

// Optional but recommended: enables better Swagger integration & customization
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    // Exposes the native OpenAPI document (e.g. /openapi/v1.json)
    app.MapOpenApi();

    // Enables Swagger UI – points to the native OpenAPI endpoint
    app.UseSwagger();
    app.UseSwaggerUI(options =>
    {
        // Use the document generated by Microsoft.AspNetCore.OpenApi
        options.SwaggerEndpoint("/openapi/v1.json", "My API v1");

        // Optional: make Swagger UI appear at the root URL[](http://localhost:<port>/)
        options.RoutePrefix = string.Empty;

        // Optional extras (uncomment if needed)
        // options.DisplayRequestDuration();           // shows timing
        // options.EnableTryItOutByDefault();          // auto-expands Try it out
        // options.EnableDeepLinking();                // better navigation
    });
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();